### ISSUE TITLE
Accept kwargs to make the interface more Pythonic

### ISSUE THREAD

**Issue by mkoeppe** [alfsan/Py4ti2#1]
Thanks for your work on this interface!
I would like to suggest the following change to make the interface more Pythonic. 

Instead of
```
groebner("mat", [[3,5,7]])
```
it would be nice if one could write
```
groebner(mat=[[3,5,7]])
```

(PyNormaliz was recently changed in the same way; you can probably adapt code from there.)

**Comment by alfsan** [comment]
Finally, a bit delayed, it's done. 

Thanks for your advice!!
